tests/test_evol.py: port assertions to python3.12.
As first identified in [Debian bug #1058334] affecting ete3, since
introduction of Python 3.12, a number of tests are failing with errors
looking like:

	AttributeError: 'Test_Coretype_ArrayTable' object has no attribute 'assert_'. Did you mean: 'assertIn'?

This is because the newer version of the unittest module of the
standard library removed the use of deprecated assert_ function for
other ones more meaningful, as documented in [Python 3.12 novelties].
It appears that there are still a few assert_ occurrences remaining in
ete4 source code, so this patch modernizes them.

[Debian bug #1058334]: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1058334
[Python 3.12 novelties]: https://docs.python.org/3/whatsnew/3.12.html#id3

Signed-off-by: Étienne Mollier <emollier@debian.org>